version: '3.6'



services:
    tester:
        build: .
        command: sh -c "python -m tests"
        volumes:
            - ./tests:/tests
            
        environment:
            SCRIPT:
            USERNAME:
            PASSWORD:
            
            
        
            
