version: '3.6'



services:
    tester:
        build: .
        command: sh -c "python -m tests"
            
        environment:
            SCRIPT:
            USERNAME:
            PASSWORD:

            
            
        
            
