version: 2.1
jobs:
  test:
    parameters:
      script:
        type: string
    docker:
      - image: docker/compose:1.23.2
    working_directory: /src

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v2-docker-{{ .Branch }}
      - restore_cache:
          keys:
            - v2-docker-list-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: Tag Docker images
          command: |
            while read REPOSITORY TAG IMAGE_ID
            do
                    echo "Tagging $REPOSITORY $TAG $IMAGE_ID"
                    docker tag "$IMAGE_ID" "$REPOSITORY:$TAG"
            done < ~/dockersimages.txt
      - run:
          name: Build Docker images
          command: docker-compose -p $CIRCLE_PROJECT_REPONAME -f .circleci/docker-compose.yaml build
          environment: 
            SCRIPT:   << script >>
      - run:
          name: Debug docker images
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}" --filter=reference="${CIRCLE_PROJECT_REPONAME}_*")
            for image in $DOCKER_IMAGES; do docker history $image; done
      - run:
          name: Save Docker layers cache
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}" --filter=reference="${CIRCLE_PROJECT_REPONAME}_*")
            DOCKER_LAYERS=$(for image in $DOCKER_IMAGES; do docker history $image -q | grep -v missing; done)
            docker save -o ~/docker-layers.tar $DOCKER_LAYERS
            docker images | sed '1d' | awk '{print $1 " " $2 " " $3}' > ~/dockersimages.txt
      - run:
          name: Test with docker-compose
          command: docker-compose -p $CIRCLE_PROJECT_REPONAME -f .circleci/docker-compose.yaml up --exit-code-from tester 
          environment: 
            SCRIPT:   << parameters.script >>

      - save_cache:
          key: v2-docker-{{ .Branch }}
          paths:
            - ~/docker-layers.tar

      - save_cache:
          key: v2-docker-list-{{ .Branch }}
          paths:
            - ~/dockersimages.txt

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: upload_single_post
          script: tests/upload_single_post.yml
      - test:
          name: print_users_feed
          script: tests/print_users_feed.yml
      - test:
          name: test prints of user feed
          script: tests/print_users_feed.yml
      - test:
          name: print_users_stories
          script: tests/print_users_stories.yml
      - test:
          name: message_some_urls
          script: tests/message_some_urls.yml
