version: 2
jobs:
  test:
    parameters:
      script:
        type: string
    docker:
      - image: docker/compose:1.23.2
    working_directory: /src/
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: Build Docker images
          command: docker-compose -p $CIRCLE_PROJECT_REPONAME -f docker-compose.test.yaml build
          environment: 
            SCRIPT:   << SCRIPT >>
      - run:
          name: Save Docker layers cache
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}" --filter=reference="${CIRCLE_PROJECT_REPONAME}_*")
            DOCKER_LAYERS=$(for image in $DOCKER_IMAGES; do docker history $image -q | grep -v missing; done)
            docker save -o ~/docker-layers.tar $DOCKER_LAYERS
      - run:
          name: Test with docker-compose
          command: docker-compose -p $CIRCLE_PROJECT_REPONAME -f docker-compose.test.yaml up --exit-code-from tester
          environment: 
            SCRIPT:   << SCRIPT >>
      - save_cache:
          key: v1-docker-{{ .Branch }}
          paths:
            - ~/docker-layers.tar

workflows:
  jobs:
    - test:
        script: tests/test_single_upload.yaml
    - test:
        script: tests/test_like.yaml
