version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: docker/compose
    working_directory: /src/
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test with docker.compose
          command: docker-compose -f docker-compose.test.yaml up 
