version: 2.1
jobs:
  test:
    parameters:
      script:
        type: string
    docker:
      - image: docker/compose:1.23.2
    working_directory: /src

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v6-docker-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true

      - run:
          name: Debug docker images before
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}" --filter=reference="${CIRCLE_PROJECT_REPONAME}_*")
            for image in $DOCKER_IMAGES; do docker history $image; done

      - run:
          name: Build with docker-compose
          command: docker-compose -p $CIRCLE_PROJECT_REPONAME -f .circleci/docker-compose.yaml build

      - run:
          name: Debug docker images after
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}" --filter=reference="${CIRCLE_PROJECT_REPONAME}_*")
            for image in $DOCKER_IMAGES; do docker history $image; done
      - run:
          name: Save Docker layers cache
          command: |
            DOCKER_IMAGES=$(docker images --format "{{.Repository}}" --filter=reference="${CIRCLE_PROJECT_REPONAME}_*")
            DOCKER_LAYERS=$(for image in $DOCKER_IMAGES; do docker history $image -q | grep -v missing; done)
            docker save -o ~/docker-layers.tar $DOCKER_LAYERS

      - save_cache:
          key: v6-docker-{{ .Branch }}
          paths:
            - ~/docker-layers.tar
      - run:
          name: Test with docker-compose
          command: docker-compose -p $CIRCLE_PROJECT_REPONAME -f .circleci/docker-compose.yaml up --abort-on-container-exit --exit-code-from tester
          environment:
            SCRIPT:   << parameters.script >>

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: upload_single_post
          script: tests/upload_single_post.yml
