version: '3.6'



services:
    tester:
        build: ../
        command: sh -c "cd / && python -m tests.circleci"
        volumes: 
            - ../tests/:/tests
            
        environment:
            SCRIPT:
            USERNAME:
            PASSWORD:

            
            
        
            
