version: '3.6'



services:
    tester:
        build: ../
        command: sh -c "cd /src && ls -1 tests && python -m tests.circleci"
        volumes: 
            - ../tests:/src/tests
            
        environment:
            SCRIPT:
            USERNAME:
            PASSWORD:

            
            
        
            
