version: '3.6'



services:
    tester:
        build: ../
        command: sh -c "pip install portalocker && python -m tests.circleci"
            
        environment:
            SCRIPT:
            USERNAME:
            PASSWORD:

            
            
        
            
