version: '3.6'



services:
    tester:
        container_name: tester
        build: ../
        command: sh -c "cd /src && ls -1 tests && python -m tests.circleci"

        environment:
            SCRIPT:
            USERNAME:
            PASSWORD:
